---
title: "PPCA Data Generation"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
library(R.matlab)
library(BiocManager)
library(pcaMethods)
library(MetabolAnalyze)
library(MASS)
library(abind)
```

```{r include=FALSE}
UE1 <- as.matrix(read.csv('../data_UE1_600/data_unfold_UE1_600.csv', row.names = 1))
UE2 <- readMat('../data_UE2_600/quadriga_ue2_snr10_avg10TTI_total600TTI_evalinterval1TTI_seed123.mat')

UE2 <- UE2[1]$param[[3]]

# Truncation of data
UE2 <- UE2[1:(dim(UE2)[1]/2),,]

unfold <- function(mat){
  
  # Unfolds Matrix "mat" with dimensions [p x sb x tti] into [tti x sb·p·2]. 
  # This 2 is stands for Re and Im Part Separated
    # p: Path
    # sb: Number of Freq Subband
    # tti: Time Transmitting Interval 
  
  # Inputs
    # mat: matrix [p x sb x tti]
  
  # Outputs
    # unfolded: matrix [tti x sb·p·2]
  
  p <- dim(mat)[1] # Paths per sb per Re or Im
  
  sb <- dim(mat)[2] 
  
  # empty matrix to be filled
  unfolded <- matrix(NA, dim(mat)[3], dim(mat)[1] * sb * 2)

  fold_iterate <- c(1:p, (2*p+1):(3*p), (4*p+1):(5*p), (6*p+1):(7*p))  
  # Iterates unfolded mat 
  
  fold_x <- 1
  
  for (i in 1:sb){ # Iterates sb (4)
    
    for  (j in 1:p){ # Iterates p
      
      subset <- mat[j,i,]

      unfolded[, fold_iterate[fold_x]]  <- Re(subset) 
      unfolded[, fold_iterate[fold_x] + p]  <- Im(subset) 

      fold_x <- fold_x + 1  
      
      }
  }
  return(unfolded)
}

UE2 <- unfold(UE2) 



```

```{r include=FALSE}

mask_data <- function(mat,mask){
  
  # Masking of the data "mat" with a mask object given
  
   # Inputs
    # data: matrix [tti x sb·p·2]
    # mask: matrix [mask_length x sb·p·2]
  
   # Outputs
    # mat: matrix [tti x sb·p·2]
  
  bracket_mask <- nrow(mask)
  
  mat[(nrow(mat)-bracket_mask+1):nrow(mat), ] <-  mask * 
    mat[(nrow(mat)-bracket_mask+1):nrow(mat), ]
  mat
  
}

len_masked <- 0
pilot_masking <- function(mat,perc){
  
  # It masks given a percentage of TTI beginning by last TTI. Periodically 
  # masking 75% of the paths except for pilot band
    # p_sb: Paths per sb per param x 2

  # Inputs
    # data: matrix [tti x sb·p·2]
    # perc: % of TTI masked 
  
  # Outputs
    # data_masked: matrix [tti x sb·p·2]
  
  p_sb <- ncol(mat)/4
  
  # find the subset of data rows that we have to mask
  
  masked_bracket_len <- floor(nrow(mat)*perc/4)*4

  # indexes for each masking pattern

  nomask_1 <- 1:p_sb
  nomask_2 <- (p_sb+1):(2*p_sb)
  nomask_3 <- (2*p_sb+1):(3*p_sb)
  nomask_4 <- (3*p_sb+1):ncol(mat)
  
  ones_row <- rep(1, ncol(mat))
  
  mask_1 <- ones_row
  mask_1[-nomask_1] <- NA
    
  mask_2 <- ones_row
  mask_2[-nomask_2] <- NA
    
  mask_3 <- ones_row
  mask_3[-nomask_3] <- NA
    
  mask_4 <- ones_row
  mask_4[-nomask_4] <- NA
    
  maskblock <- rbind(mask_1,  mask_3, mask_2, mask_4)
  
  multiplicator <- masked_bracket_len/4
  
  mask <- do.call(rbind, replicate(multiplicator, maskblock, simplify=FALSE)) 
  
  len_masked <<- nrow(mask)
  
  mask_data(mat, mask)
  
}

masked_dataUE1 <- pilot_masking(UE1,0.4)
masked_dataUE2 <- pilot_masking(UE2,0.4)

```

```{r include=FALSE}

#write.csv(masked_dataUE1, '../data2UEjoint/masked_data_UE1.csv')
#write.csv(masked_dataUE2, '../data2UEjoint/masked_data_UE2.csv')

#write.csv(UE1,'../data2UEjoint/data_unfold_UE1_600.csv')
#write.csv(UE2,'../data2UEjoint/data_unfold_UE2_600.csv')


```


```{r include=FALSE}
# UE1

a <- (rep(NA, ncol(UE1)))
a <- rbind(a, a)
data_aux <- rbind(a, UE1)

masked_data <- pilot_masking(data_aux,1)
masked_data_UE1 <- masked_data[3:nrow(masked_data),]
  
# UE2

a <- (rep(NA, ncol(UE2)))
a <- rbind(a, a)
data_aux <- rbind(a, UE2)

masked_data <- pilot_masking(data_aux,1)
masked_data_UE2 <- masked_data[3:nrow(masked_data),]


```

```{r include=FALSE}
# Generate X values NN

X1 <- t(apply(masked_data_UE1, function(x) x[!is.na(x)], MARGIN = 1))
masked_idx <- is.na(masked_data_UE1)

# Generate y Values for NN

y1 <- matrix(nrow = nrow(X1), ncol=3*(ncol(masked_data_UE1)/4))
  
for (i in 1:nrow(masked_idx)){
  idx_row <- which(masked_idx[i,])
  row <- UE1[i,idx_row]
  y1[i,] <- row
}

#write.csv(X, '../data_UE1_600/X_600_TTI.csv')
#write.csv(y, '../data_UE1_600/y_600_TTI.csv')

```

```{r include=FALSE}
# Generate X values NN

X2 <- t(apply(masked_data_UE2, function(x) x[!is.na(x)], MARGIN = 1))
masked_idx <- is.na(masked_data_UE2)

# Generate y Values for NN

y2 <- matrix(nrow = nrow(X2), ncol=3*(ncol(masked_data_UE2)/4))
  
for (i in 1:nrow(masked_idx)){
  idx_row <- which(masked_idx[i,])
  row <- UE2[i,idx_row]
  y2[i,] <- row
}



#write.csv(X, '../data2UEjoint/X_joint.csv')
#write.csv(y, '../data2UEjoint/y_joint.csv')

```

```{r include=FALSE}
X1_train <- X1[1:(nrow(X1)-236 ), ]
y1_train <- y1[1:(nrow(y1)-236 ), ]
X1_valid <- X1[(nrow(X1)-235 ): nrow(X1), ]
y1_valid <- y1[(nrow(y1)-235 ): nrow(y1), ]

```

```{r include=FALSE}
X2_train <- X2[1:(nrow(X2)-236 ), ]
y2_train <- y2[1:(nrow(y2)-236 ), ]
X2_valid <- X2[(nrow(X2)-235 ): nrow(X2), ]
y2_valid <- y2[(nrow(y2)-235 ): nrow(y2), ]

```

```{r include=FALSE}
X_train <- rbind(X1_train, X2_train)
y_train <- rbind(y1_train, y2_train)
X_valid <- rbind(X1_valid, X1_valid)
y_valid <- rbind(y1_valid, y2_valid)
```

```{r include=FALSE}

#write.csv(X_train, '../data2UEjoint/X_train_joint.csv')
#write.csv(y_train, '../data2UEjoint/y_train_joint.csv')
#write.csv(X_valid, '../data2UEjoint/X_valid_joint.csv')
#write.csv(y_valid, '../data2UEjoint/y_valid_joint.csv')
```

# Appendix: All code for this report

```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```


