---
title: "PPCA Data Generation"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r include=FALSE}
library(R.matlab)
library(BiocManager)
library(pcaMethods)
library(MetabolAnalyze)
library(MASS)
library(abind)
source("../../../Preprocessing_Utilities.R")
source("../../../PPCA_Utilities.R")
source("../../../FoldMatrix.R")
```

```{r include=FALSE}
data <- readMat("../../../../Data/data_UE1_600/quadriga_ue1_snr10_avg10TTI_total600TTI_evalinterval1TTI_seed123.mat") 

mat <- data$amp

# Truncation of data
mat <- data[1]$param[[3]]

# Truncation of data
mat <- mat[1:(dim(mat)[1]/2),,]



data <- unfold_polar(mat) 
```

```{r include=FALSE}
write.csv(data,'UE1_data_unfold_arg_polar.csv')
```


```{r include=FALSE}

len_masked <- 0

masked_data <- pilot_masking(data,0.4)

write.csv(masked_data, 'masked_data_04_arg.csv')
```

```{r include=FALSE}
#data <- as.matrix(read.csv('../data_90TTI/data_unfold_arg.csv', row.names = 1))

a <- (rep(NA, ncol(data)))
a <- rbind(a, a)
data_aux <- rbind(a, data)

masked_data <- pilot_masking(data_aux,1)
masked_data <- masked_data[3:nrow(masked_data), ]

write.csv(masked_data, 'masked_data_full_arg.csv')

```


## 2nd Polarisation

```{r include=FALSE}
data <- readMat("../../../../Data/data_UE1_600/quadriga_ue1_snr10_avg10TTI_total600TTI_evalinterval1TTI_seed123.mat") 

mat <- data[1]$param[[3]]


# Truncation of data
mat <- mat[((dim(mat)[1]/2)+1):nrow(mat),,]


data <- unfold(mat) 






write.csv(data,'../../../../Baseline/PPCA/Baseline_UE1/Polar/UE1_data_unfold_arg_polar_2.csv')
```


# Appendix: All code for this report

```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```


